In [3]:
import pandas
df = pandas.read_csv("tmdb.csv")
df.isnull() # 查看数据中是否有缺失值
df.dropna() # 删除数据中缺失值所在的行
df.ffill() # 用上一行的数据填充缺失值
df.bfill() # 用下一行的数据填充缺失值
df.fillna("--") # 用指定值填充缺失值

df.duplicated() # 查看数据中是否有重复数据
df.duplicated(subset=["年份", "评分"]) # 查看数据中指定列是否有重复数据
df.drop_duplicates(subset=["年份", "评分"]) # 删除数据中指定列的重复数据

df[df["时长"] >= 300] #查看异常值
df.drop(df[df["时长"] >= 300].index) # 删除异常值
df["时长"] = df["时长"].abs() # 处理异常值

df["时长"].astype("str").str.replace("$","分钟",regex=True)

0       142.0分钟
1       175.0分钟
2       200.0分钟
3       195.0分钟
4       100.0分钟
         ...
1995    103.0分钟
1996    215.0分钟
1997    144.0分钟
1998    124.0分钟
1999     93.0分钟
Name: 时长, Length: 2000, dtype: object

In [12]:
df.sort_values("年份",ascending= False)
df.sort_values(["年份","评分"],ascending=[False,True])

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,主演,Slogan,简介
1091,河狸变身计划,2026,2026-03-20,动画 家庭 科幻 喜剧 冒险,99.0,76,英语,丹尼尔·钟,杰西·安德鲁斯,派珀·柯达 鲍比·莫伊尼汉 乔恩·哈姆 凯茜·纳基麦 戴夫·弗兰科 爱德华多·佛朗哥 Apa...,表现得自然一点。,梅宝是一位对动物世界充满好奇的年轻女孩，她利用先进的意识上传技术，将自己的思维注入一只机械河...
499,奇迹梦之队,2026,2026-03-14,动画 喜剧 家庭,100.0,79,英语,泰瑞·迪利,泰迪·赖利,凯莱布·麦克劳克林 加布里埃尔·尤尼恩 斯蒂芬·科里 亚伦·皮埃尔 妮可拉·考夫兰 大卫·哈...,梦想从不因渺小而受限。,主角威尔是只梦想成为职业球手的小山羊，面对向来由猛兽主宰的凶险赛场，队友对他嗤之以鼻，他能否...
139,挽救计划,2026,2026-03-20,科幻 冒险,157.0,82,英语,菲尔·洛德,克里斯托弗·米勒,瑞恩·高斯林 詹姆斯·奥尔蒂斯 桑德拉·惠勒 莱昂内尔·博伊斯 米拉娜·薇恩翠 肯·兰格 普...,相信奇迹会发生。,太阳即将熄灭，地球命悬一线，对太空一窍不通的中学老师瑞恩（瑞恩·高斯林 饰）竟成为全人类的希...
1712,恩典,2025,2025-12-25,剧情,133.0,74,意大利语,保罗·索伦蒂诺,NaN,Toni Servillo Anna Ferzetti Massimo Venturiell...,A president. A pardon. A legacy.,马里亚诺·德·桑蒂斯是意大利共和国总统。此人与现实中的任何总统均无关联，完全是作者虚构的人物...
1758,至尊马蒂,2025,2026-03-20,剧情 惊悚,150.0,74,英语,约书亚·萨弗迪,罗纳德·布朗斯坦,提莫西·查拉梅 格温妮斯·帕特洛 奥德萨·阿兹恩 凯文·奥利里 泰勒·奥康马 弗朗辛·德雷舍...,志存高远。,为了实现一个无人相信的伟大梦想，马蒂去了一趟地狱。年轻迷人的马蒂，渴望名声、荣耀，以及遥不可...
...,...,...,...,...,...,...,...,...,...,...,...,...
675,幽灵马车,1921,1921-01-01,剧情 奇幻 恐怖,108.0,78,瑞典语,维克多·斯约斯特洛姆,Selma Lagerlöf,维克多·斯约斯特洛姆 Hilda Borgström Tore Svennberg Astr...,Do the Dead Come Back? Can Your Soul Leave You...,故事发生在新年来临之夜，传说每年的这个夜晚，死神就会来到人间挑选一个罪孽深重的人来驾驶他的马...
167,寻子遇仙记,1921,1928-04-29,喜剧 剧情,68.0,81,英语,查理·卓别林,NaN,查理·卓别林 杰基·库根 卡尔·米勒 埃德娜·普维恩斯 阿尔伯特·奥斯汀 比尤拉 波因斯 内...,六卷欢乐。,当查理·卓别林决定突破短片形式、创作其首部长片时，他已是国际巨星。本片不仅展现了卓别林职业生...
401,卡里加里博士的小屋,1920,1920-02-27,剧情 恐怖 惊悚 犯罪,77.0,79,德语,罗伯特·维内,汉斯·雅诺维茨,Werner Krauss 康拉德·维特 Friedrich Fehér Lil Dagov...,You must become Caligari!,德国小镇，面目狰狞的卡里加里博士（沃纳·克劳斯 Werner Krauss饰）终于获准表演催...
432,一周,1920,1920-08-29,喜剧,19.0,79,No Language,爱德华·克莱因,巴斯特·基頓,巴斯特·基頓 Sybil Seely 乔·罗伯茨,两卷令人捧腹的欢乐片段，源自蜜月者的考验......,本部黑白短片讲述一对儿新婚燕尔的小夫妻，在一个星期里搭建他们的“便携式新房”的温馨小故事。九...
434,月球旅行记,1902,2012-06-19,历史 冒险 科幻,14.0,79,法语,乔治·梅里爱,儒勒·凡尔纳,乔治·梅里爱 Bleuette Bernon François Lallement Jeha...,The first science fiction film!,天文学院院长（乔治·梅里爱 Georges Méliès 饰）在一次会议上提出天马行空的月球...

In [32]:
df.groupby("年份")["电影名"].count()
df.groupby("年份")["评分"].sum()
df.groupby("年份")["评分"].min()
df.groupby("年份")["评分"].max()
df.groupby("年份")["评分"].mean()
df.groupby("年份")["评分"].aggregate(["count","sum","min","max","mean"])
df.groupby("年份").aggregate({"评分":["count","sum","min","max","mean"],
                              "时长":["count","sum","min","max","mean"]})

        评分                             时长
     count   sum min max       mean count     sum   min    max        mean
年份
1902     1    79  79  79  79.000000     1    14.0  14.0   14.0   14.000000
1920     2   158  79  79  79.000000     2    96.0  19.0   77.0   48.000000
1921     2   159  78  81  79.500000     2   176.0  68.0  108.0   88.000000
1922     2   153  76  77  76.500000     2   194.0  89.0  105.0   97.000000
1923     2   152  75  77  76.000000     2   146.0  73.0   73.0   73.000000
...    ...   ...  ..  ..        ...   ...     ...   ...    ...         ...
2022    70  5376  74  85  76.800000    70  8329.0  35.0  193.0  118.985714
2023    53  4104  73  86  77.433962    53  6361.0   9.0  206.0  120.018868
2024    31  2403  74  83  77.516129    31  3536.0  50.0  178.0  114.064516
2025    29  2229  74  84  76.862069    29  3520.0  28.0  197.0  121.379310
2026     3   237  76  82  79.000000     3   356.0  99.0  157.0  118.666667

[108 rows x 10 columns]