In [3]:
import pandas

df = pandas.DataFrame([
    {"姓名": "张三","语文": 80,"数学": 90,"英语":100},
    {"姓名": "李四","语文": 90,"数学": 80,"英语":90},
    {"姓名": "王五","语文": 100,"数学": 100,"英语":80},
    {"姓名": "赵六","语文": 80,"数学": 90,"英语":100},
    {"姓名": "孙七","语文": 90,"数学": 80,"英语":90},
    {"姓名": "周八","语文": 100,"数学": 100,"英语":80},
    {"姓名": "吴九","语文": 80,"数学": 90,"英语":100},
    {"姓名": "郑十","语文": 90,"数学": 80,"英语":90},
    {"姓名": "王十一","语文": 100,"数学": 100,"英语":80},
    {"姓名": "张十二","语文": 80,"数学": 90,"英语":100},
    {"姓名": "李十三","语文": 90,"数学": 80,"英语":90},
])

print(df)
print(f"{df['语文'].min()},{df['语文'].max()},{df['语文'].mean():.2f},{df['语文'].sum()}")

     姓名   语文   数学   英语
0    张三   80   90  100
1    李四   90   80   90
2    王五  100  100   80
3    赵六   80   90  100
4    孙七   90   80   90
5    周八  100  100   80
6    吴九   80   90  100
7    郑十   90   80   90
8   王十一  100  100   80
9   张十二   80   90  100
10  李十三   90   80   90
80,100,89.09,980

In [4]:
print(df.index.tolist())
print(df.columns.tolist())
print(df.values.tolist())
print(df.size)
print(df.dtypes)
print(df.shape)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
['姓名', '语文', '数学', '英语']
[['张三', 80, 90, 100], ['李四', 90, 80, 90], ['王五', 100, 100, 80], ['赵六', 80, 90, 100], ['孙七', 90, 80, 90], ['周八', 100, 100, 80], ['吴九', 80, 90, 100], ['郑十', 90, 80, 90], ['王十一', 100, 100, 80], ['张十二', 80, 90, 100], ['李十三', 90, 80, 90]]
44
姓名    object
语文     int64
数学     int64
英语     int64
dtype: object
(11, 4)

In [5]:
tmdb_df = pandas.read_csv("tmdb.csv",usecols=['电影名', '年份', '类型', '时长', '评分', '语言'])
tmdb_df["test"] = tmdb_df["时长"] * tmdb_df["评分"]
tmdb_df.to_csv("tmdb_test.csv",index=False)
tmdb_df

                        电影名    年份           类型     时长  评分  语言     test
0                    肖申克的救赎  1994        剧情 犯罪  142.0  87  英语  12354.0
1                        教父  1972        剧情 犯罪  175.0  87  英语  15225.0
2                       教父2  1974        剧情 犯罪  200.0  86  英语  17200.0
3                    辛德勒的名单  1993     剧情 历史 战争  195.0  86  英语  16770.0
4     ¿Quieres ser mi hijo?  2023        喜剧 爱情  100.0  86  英语   8600.0
...                     ...   ...          ...    ...  ..  ..      ...
1995                  绣巾蒙面盗  1946     犯罪 悬疑 惊悚  103.0  73  英语   7519.0
1996                    守望者  2009     悬疑 动作 科幻  215.0  74  英语  15910.0
1997                  战略大作战  1970     冒险 喜剧 战争  144.0  74  英语  10656.0
1998                    大毒枭  2001        犯罪 剧情  124.0  74  英语   9176.0
1999                  飞鸭向前冲  2023  家庭 喜剧 冒险 动画   93.0  73  英语   6789.0

[2000 rows x 7 columns]

In [6]:
test_df = pandas.read_csv("tmdb.csv")
test_df.head(50)
test_df.tail(50)
test_df.describe()
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   电影名     2000 non-null   object
 1   年份      2000 non-null   int64
 2   上映时间    2000 non-null   object
 3   类型      2000 non-null   object
 4   时长      1998 non-null   float64
 5   评分      2000 non-null   int64
 6   语言      2000 non-null   object
 7   导演      1998 non-null   object
 8   作者      1584 non-null   object
 9   主演      1990 non-null   object
 10  Slogan  1688 non-null   object
 11  简介      2000 non-null   object
dtypes: float64(1), int64(2), object(9)
memory usage: 187.6+ KB

In [7]:
test_df["电影名"]
test_df[["电影名","评分"]]
test_df.iloc[50:100:2]
test_df.loc[50:100:1]

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,主演,Slogan,简介
50,天国与地狱,1963,1963-03-01,剧情 犯罪 惊悚,142.0,84,日语,黑泽明,埃文·亨特,三船敏郎 仲代达矢 香川京子 三桥达也 木村功 石山健二郎 加藤武 志村乔 田崎润,剧情紧张激烈，几乎令人难以置信！,在黑泽明这部极具影响力的家庭伦理剧与刑侦叙事杰作中，三船敏郎饰演的富商权藤金吾令人过目难忘—...
51,沉默的羔羊,1991,2018-04-16,犯罪 惊悚 剧情,119.0,83,英语,乔纳森·戴米,托马斯·哈里斯,朱迪·福斯特 安东尼·霍普金斯 斯科特·格伦 泰德·拉文 安东尼·希尔德 布鲁克·史密斯 黛...,要进入杀手的头脑，她必须挑战疯子的头脑。,在这部改编自托马斯·哈里斯畅销小说的惊世之作中，技艺超凡的导演乔纳森·戴米以令人毛骨悚然的笔...
52,后窗,1954,2019-04-13,惊悚 悬疑,112.0,83,英语,阿尔弗雷德·希区柯克,约翰·迈克尔·海耶斯,詹姆斯·斯图尔特 格蕾丝·凯利 温德尔·科里 塞尔玛·里特 雷蒙德·伯尔 朱迪思·伊芙琳 罗...,只需一个目击者，就能破坏这桩完美的犯罪。,一位足不出户的摄影师透过公寓窗户窥见邻居们的隐秘生活，当他断定其中一人犯下谋杀罪行时，一场扣...
53,带来灵魂：防弹少年团演唱会电影,2019,2019-08-07,音乐 纪录,103.0,83,朝鲜语,Park Jun-soo,NaN,RM Jin SUGA j-hope Jimin 金泰亨 田柾国,"Forever, we are young.",据媒体报道防弹少年团 第三部演唱会电影《Bring the Soul：The Movie》确...
54,蜘蛛侠：纵横宇宙,2023,2023-06-02,动画 动作 冒险 科幻,140.0,83,英语,乔伊姆·多斯·桑托斯,贾斯汀·K·汤普森,沙梅克·摩尔 海莉·斯坦菲尔德 布莱恩·泰里·亨利 劳伦·贝莱斯 杰克·约翰逊 奥斯卡·伊萨...,每个人都说这是蜘蛛侠注定的命运，但我要找到属于自己的路。,荣获奥斯卡奖的蜘蛛侠平行宇宙传奇迎来全新篇章。在这段史诗级冒险中，布鲁克林的全职邻家英雄蜘蛛...
55,美国X档案,1998,1998-10-30,剧情,119.0,83,英语,托尼·凯耶,大卫·麦肯纳,爱德华·诺顿 爱德华·弗朗 贝弗利·德安杰洛 詹妮弗·林 伊桑·苏普利 费尔鲁扎·鲍克 艾弗...,Some legacies must end.,德瑞克 的父亲在他很小的时候就被一名黑人毒贩射杀，从此给他幼小的心灵埋下了仇恨的种子。原来德...
56,回到未来,1985,1985-07-03,冒险 喜剧 科幻,116.0,83,英语,罗伯特·泽米吉斯,鲍勃·盖尔,迈克尔·J·福克斯 克里斯托弗·劳埃德 克里斯平·格洛弗 莉·汤普森 克劳迪娅·韦尔斯 托马...,他是唯一一个到出生前惹麻烦的孩子。,马蒂·麦克弗莱，一位典型的八十年代美国青少年，意外被一台由钚动力驱动的德罗宁“时间机器”送回...
57,幽灵公主,1997,2025-05-01,冒险 奇幻 动画,134.0,83,日语,宫崎骏,NaN,松田洋治 石田百合子 田中裕子 小林薰 西村雅彦 上条恒彦 美轮明宏 森光子 森繁久弥,世界的命运系于一位勇士的勇气之上。,室町时代时期的虾夷族少年阿席达卡，某日遇到被称为“邪魔神”攻击他所居住村落的怪物。在阿席达卡...
58,激进教学,2023,2023-10-19,剧情,122.0,83,西班牙语,Christopher Zalla,NaN,欧亨尼奥·德伯兹 Daniel Haddad Jennifer Trejo Mia Fern...,Think for yourself.,在一个充满忽视、腐败和暴力的墨西哥边境小镇，一名老师决定尝试一种激进的新方法来释放学生的潜力...
59,电锯人剧场版：蕾塞篇,2025,2025-09-19,动画 动作 爱情 奇幻,100.0,83,日语,吉原达矢,濑古浩司,户谷菊之介 上田丽奈 楠木灯 坂田将吾 内田真礼 花江夏树 高桥花林 菲鲁兹·蓝 内田夕夜,活出你的人生本色……并让它精彩纷呈。,故事延续TV动画的最终章，讲述男主角电次在偶然邂逅的神秘少女蕾塞的庇护下，在快节奏的战斗中，...
60,别假正经,1984,2024-06-16,纪录 音乐,88.0,83,英语,乔纳森·戴米,NaN,大卫·伯恩 Chris Frantz Jerry Harrison Tina Weymout...,Why stop making sense? Why a movie? Why a big ...,一部关于摇滚乐队传声头的演唱会纪实电影。
61,五等分的新娘 剧场版,2022,2022-05-20,动画 喜剧 爱情,136.0,83,日语,神保昌登,大知庆一郎,松冈祯丞 花泽香菜 竹达彩奈 伊藤美来 佐仓绫音 水濑祈 高森奈津美 日野聪,NaN,为了让「濒临留级」又「讨厌学习」的美少女五姐妹通过学校考试毕业，主角风太郎以兼职家庭教师的身...
62,生之欲,1952,1952-10-09,剧情,143.0,83,日语,黑泽明,桥本忍,志村乔 田中春男 金子信雄 左卜全 小田切美喜 日守新一 千秋实 山田巳之助 藤原釜足,一个关于小人物的大故事，它将紧紧抓住你的灵魂……,黑泽明导演生涯的至高成就之一，本片以极致的悲悯凝视死亡，完成对生命的礼赞。志村乔动人诠释胃癌...
63,荒野机器人,2024,2024-09-20,家庭 动画 科幻 冒险,102.0,83,英语,克里斯·桑德斯,彼得·布朗,露皮塔·尼永奥 佩德罗·帕斯卡 基特·康纳 比尔·奈伊 许玮伦 马修·贝瑞 文·瑞姆斯 马克...,发现你的本性,梦工厂动画全新改编文学畅销作品——彼得·布朗荣获大奖、备受喜爱的《纽约时报》榜首畅销书《荒野...
64,同级生,2016,2016-02-20,爱情 动画,61.0,83,日语,中村章子,中村明日美子,野岛健儿 神谷浩史 石川英郎 Yurino,"Sincerely, Slowly, Falling in Love.",夏天时节，东府第一高校要举行合唱祭。在课后合唱训练中，高中二年级A班草壁光（神谷浩史 配音）...
65,紫罗兰永恒花园 剧场版,2020,2021-12-25,动画 剧情 奇幻 爱情,140.0,83,日语,石立太一,晓佳奈,石川由依 浪川大辅 子安武人 木内秀信 户松遥 内山昂辉 远藤绫 茅原实里 水桥香织,致我最心爱的人，这是我最后的书信。,——「爱」究竟是什么？ 曾经将「爱」告诉自己、 给予自己的，重要的人。 即使想见，却再也...
66,未麻的部屋,1998,2024-04-18,动画 惊悚,82.0,83,日语,今敏,竹内义和,岩男润子 松本梨香 新山志保 大仓正章 辻亲八 古川惠实子 秋元羊介 盐屋翼 堀秀行,不好意思……请问你是？,当红三人少女偶像团体Charming Bird面临解散，核心成员雾越未麻在事务所的安排下不得...
67,罗小黑战记,2019,2019-08-27,动画 奇幻 动作,102.0,83,汉语,MTJJ,彭可欣,王宥霁 刘明月 郝祥海 叮当 曹云图 冯盛 陈思宇,有你的地方 就是家,在熙攘的人类世界里，很多妖精隐匿其中，他们与人类相安无事地生活着。猫妖罗小黑因为家园被破坏，...
68,死亡诗社,1989,1989-06-02,剧情,128.0,83,英语,彼得·威尔,托马斯·舒尔曼,罗宾·威廉姆斯 罗伯特·肖恩·莱纳德 伊桑·霍克 乔西·查尔斯 盖尔·汉森 迪伦·库斯曼 阿...,He was their inspiration. He made their lives ...,威尔顿预备学院以其沉稳凝重的教学风格和较高的升学率闻名，作为其毕业班的学生，理想就是升入名校...
69,音魂掠影,2022,2022-02-17,纪录 音乐 历史,156.0,83,意大利语,朱塞佩·托纳多雷,NaN,埃尼奥·莫里康内 西尔瓦诺·阿戈斯蒂 亚历山德罗·亚历山德罗尼 Fausto Ancilla...,NaN,由著名导演#朱塞佩·托纳多雷#编剧并执导，吉亚尼·罗素、王家卫等人任监制，聚焦意大利音乐大师...
70,这个杀手不太冷,1994,2024-11-01,犯罪 剧情 动作,133.0,83,法语,吕克·贝松,NaN,让·雷诺 娜塔莉·波特曼 加里·奥德曼 丹尼尔·艾洛 彼得·阿佩尔 迈克尔·巴达卢科 艾伦·...,想把事情办的漂亮，就得请专业的,里昂是名孤独的职业杀手，受人雇佣。一天，邻居家小姑娘马蒂尔达敲开他的房门，要求在他那里暂避杀...
71,我们如此相爱,1974,1974-12-21,剧情 喜剧,124.0,83,意大利语,Ettore Scola,艾根诺尔·因克鲁西,Nino Manfredi 维托里奥·加斯曼 斯特法尼娅·桑德雷莉 Stefano Satt...,A many splendored thing.,安东尼奥（尼诺·曼弗莱迪 Nino Manfredi 饰）、贾尼（维托里奥·加斯曼 Vitt...
72,献给我的前妻,2019,2019-11-08,剧情 喜剧,94.0,83,西班牙语,Jorge Ulloa,Diego Ulloa,Raúl Santana Nataly Valencia Carlos Alcántara ...,NaN,这部电影讲述了21岁的阿里尔的故事：为筹钱挽回濒临破裂的恋情、与前女友重逢，他决定组建一支摇...
73,大独裁者,1940,2021-09-19,喜剧 战争,125.0,83,英语,查理·卓别林,NaN,查理·卓别林 波莱特·戈达德 杰克·奥基 雷金纳德·加德纳 亨利·丹尼尔 比利·吉尔伯特 格...,再次——全世界都在嘲笑！,在其备受争议的杰作中，查理·卓别林既尖刻地讽刺了阿道夫·希特勒，又巧妙地颠覆了自身的喜剧形象...
74,从前有个工作室,2023,2023-11-24,动画 家庭 奇幻 剧情 喜剧,9.0,83,英语,Trent Correy,Dan Abraham,克里斯·迪曼托波罗斯 凯特琳·罗布罗克 Tony Anselmo Bill Farmer 吉...,100 years of Disney magic comes together.,短片为迪士尼成立满100周年的纪念作品，导演崔伦特·柯瑞和丹·亚伯拉罕花了大约八个月时间构思...
75,生活多美好,1946,1946-12-20,剧情 家庭 奇幻,131.0,83,英语,弗兰克·卡普拉,弗朗西丝·古德里奇,詹姆斯·斯图尔特 唐娜·里德 莱昂内尔·巴里摩尔 托马斯·米切尔 亨利·特拉弗斯 比尤拉·邦...,这笑声多么美妙！这爱意多么动人！,一位天使被派往人间，帮助一位万念俱灰的商人，向他展现假如他从未存在过，生活将会是怎样的光景。
76,摩登时代,1936,1936-09-17,喜剧 剧情 爱情,87.0,83,英语,查理·卓别林,NaN,查理·卓别林 波莱特·戈达德 亨利·伯格曼 蒂尼·桑福德 切斯特·康克林 汉克·曼恩 斯坦利...,他是现代最伟大的艺人，举世无双！世上无人能像他那样，让你开怀大笑，又深深触动你的心弦……全世...,二十年代的美国处于经济萧条时期，失业率居高不下，工人受尽压榨，成为了大机器生产中的一颗螺丝钉...
77,日落大道,1950,1950-08-10,剧情,110.0,83,英语,比利·怀尔德,查尔斯·威廉·布莱克特,威廉·霍尔顿 格洛丽亚·斯旺森 埃里克·冯·施特罗海姆 南希·奥尔森 弗雷德·克拉克 劳埃德...,一个好莱坞故事。,好莱坞的声名终会消散——只需问问诺玛·戴斯蒙德。她曾是影坛传奇，如今已成被人遗忘的旧时代残影...
78,西部往事,1968,2018-04-16,剧情 西部,166.0,83,意大利语,赛尔乔·莱昂内,塞尔吉奥·多纳蒂,克劳迪娅·卡汀娜 亨利·方达 杰森·罗巴兹 查尔斯·布朗森 加布里埃尔·费泽蒂 Paolo ...,她生命中有三个男人。一个带走了她，一个深爱着她，还有一个——最终杀死了她。,塞尔吉奥·莱昂内的这部不朽史诗，其恢弘堪比取景地纪念碑谷，其气度媲美星光熠熠的杰出演员阵容，...
79,触不可及,2011,2011-11-02,剧情 喜剧,112.0,83,法语,埃里克·托莱达诺,奥利维埃·纳卡什,弗朗索瓦·克鲁塞 奥玛·希 安娜·勒尼 奥黛丽·弗洛罗 Joséphine de Meaux...,Sometimes you have to reach into someone else'...,因为一次跳伞事故，白人富翁菲利普Philippe（弗朗索瓦·克鲁塞 François Clu...
80,现代启示录,1979,1979-05-19,剧情 战争,202.0,83,英语,弗朗西斯·科波拉,约翰·米利厄斯,马丁·辛 马龙·白兰度 弗雷德里克·福雷斯特 阿尔伯特·海尔 劳伦斯·菲什伯恩 山姆·伯顿斯...,这就是终点...,越战期间，威拉德上尉受命执行一项危险任务，深入柬埔寨刺杀一位脱离建制的叛变上校——此人已在当...
81,新世纪福音战士剧场版：Air / 真心为你,1997,1997-07-19,动画 科幻 剧情 奇幻,87.0,83,日语,庵野秀明,鹤卷和哉,绪方惠美 林原惠美 三石琴乃 宫村优子 立木文彦 长泽美树 子安武人 优希比吕 山口由里子,毁灭的命运亦是重生的喜悦。,《新世纪福音战士》系列第二部剧场版，于 1997 年 7 月 19 日在日本上映。全名：《新...
82,牯岭街少年杀人事件,1991,1991-07-27,犯罪 剧情 爱情,237.0,83,汉语,杨德昌,鸿鸿,张震 杨静怡 张国柱 金燕玲 王琄 张翰 姜秀琼 赖梵耘 谭至刚,NaN,这部由杨德昌执导的台湾电影杰作，被誉为当代影坛最受推崇与渴求的作品之一。影片以六十年代初的台...
83,青春猪头少年不会梦到怀梦美少女,2019,2019-06-15,动画 爱情 剧情 奇幻,90.0,83,日语,增井壮一,鸭志田一,石川界人 濑户麻沙美 水濑祈 东山奈央 种崎敦美 内田真礼 久保由利香 内田雄马 佐藤聪美,时间与记忆、我都一起带到未来,居住在天空与海洋辉映的城镇“藤泽”的梓川咲太，就读高中二年级。
84,GIVEN 被赠与的未来 剧场版,2020,2020-08-22,动画 剧情 音乐 爱情,59.0,83,日语,山口光,绫奈由仁子,江口拓也 中泽匡智 矢野奖吾 内田雄马 浅沼晋太郎,想要在你身边继续歌唱,高中生上山立夏热爱演奏吉他，与春树和秋彦合组一个小乐队。某个午休，他意外帮佐藤真冬修好吉他弦...
85,从天而降,2019,2019-12-24,喜剧 剧情 音乐,112.0,83,西班牙语,Pepe Bojórquez,Alfredo Felix-Diaz,奥马尔·查帕罗 安娜·克劳迪娅·塔兰孔 Stephanie Cayo Lupita Sand...,NaN,墨西哥传奇人物佩德罗·因凡特（Pedro Infante）在地球上又获得了一次机会，可以为自...
86,乔西的虎与鱼,2020,2021-06-11,动画 剧情 爱情,98.0,83,日语,田村耕太郎,桑村沙耶香,中川大志 清原果耶 宫本侑芽 兴津和幸 琳恩 松寺千惠美 尾花宽治 盛山晋太郎 内田夕夜,Together they can fly.,专攻海洋生物学的恒夫，为了实现自己能够亲眼看一下只生活在墨西哥的梦幻鱼群的梦想，日夜不停地在...
87,光荣之路,1957,1957-12-20,战争 剧情,87.0,83,英语,斯坦利·库布里克,汉弗莱·科布,柯克·道格拉斯 拉尔夫·米克尔 阿道夫·门吉欧 乔治·麦克雷迪 韦恩·莫里斯 理查德·安德森...,一将功成万骨枯,斯坦利·库布里克执导，堪称影史最具震撼力的反战电影之一。柯克·道格拉斯以炽烈演技诠释第一次世...
88,城市之光,1931,1931-03-07,喜剧 剧情 爱情,87.0,83,英语,查理·卓别林,哈里·克罗克,查理·卓别林 弗吉尼亚·切里尔 弗洛伦斯·李 哈里·迈尔斯 阿尔·欧内斯特·加西亚 汉克·曼...,真爱盲目。,这部查理·卓别林最受珍爱的作品，亦是其流浪汉形象的终极篇章。在这部无声影片中，身兼编剧、导演...
89,夜与雾,1956,1956-01-29,纪录 历史,32.0,83,法语,阿伦·雷乃,让·凯罗尔,Michel Bouquet Reinhard Heydrich Heinrich Himm...,NaN,1956年导演阿伦•雷乃用摄影机带领观众重回奥斯维辛。当年纳粹集中营的旧址上已是一片祥和美丽...
90,七号房的礼物,2019,2020-10-15,剧情,132.0,83,土耳其语,Mehmet Ada Öztekin,Kubilay Tat,Aras Bulut Iynemli 妮莎·索菲亚·阿克松古尔 İlker Aksum Me...,NaN,梅莫（阿拉斯·布鲁特·伊涅姆利 Aras Bulut Iynemli 饰）虽然生得人高马大，...
91,萤火之森,2011,2011-09-17,爱情 动画 奇幻,44.0,83,日语,大森贵弘,NaN,泽田泉 田谷隼 佐仓绫音 内山昂辉 辻亲八 山本兼平 町田政则 内田爱美 后藤弘树,我已经等不到夏天了,某年夏天，6岁小女孩竹川萤来到爷爷家度假，她闯进了传说住满妖怪的山神森林。正当她因为迷路而焦...
92,狮子王,1994,1995-07-15,动画 家庭 剧情 冒险,89.0,83,英语,罗布·明科夫,罗杰·艾勒斯,马修·布罗德里克 莫伊拉·凯利 内森·莱恩 欧内斯特·萨贝拉 詹姆斯·厄尔·琼斯 杰瑞米·艾...,最伟大的冒险，莫过于在生命的轮回中找到属于自己的位置。,辛巴是荣耀王国的小王子，他的父亲穆法沙是一个威严的国王。然而叔叔刀疤却对穆法沙的王位觊觎已久...
93,洞,1960,1960-03-18,剧情 惊悚 犯罪,132.0,83,法语,雅克·贝克,何塞·乔凡尼,Michel Constantin Jean Keraudy Philippe Leroy ...,Poor Gaspard...,在巴黎的一间牢房里，五名囚犯用尽全部的坚韧与智慧，试图通过精心挖掘的隧道重获自由。根据若泽·...
94,海上钢琴师,1998,2019-11-09,剧情 音乐,170.0,82,意大利语,朱塞佩·托纳多雷,亚历山德罗·巴里科,蒂姆·罗斯 普路特·泰勒·文斯 梅兰尼·蒂埃里 比尔·努恩 加布里埃尔·拉维亚 克兰伦斯·威...,这是一个关于一个无所不能的男人的史诗故事……唯独无法平凡。,男主角1900（人名）是一个被人遗弃在蒸气船上的孤儿，被船上一位好心的烧炉工收养，然而好人不...
95,防弹少年团世界巡回演唱会：在首尔爱自己,2019,2019-01-26,音乐 纪录,113.0,82,朝鲜语,Son Sung-deuk,NaN,RM Jin SUGA j-hope Jimin 金泰亨 田柾国,NaN,"在 BTS 世界巡回演唱会 ""Love Yourself ""期间于首尔奥林匹克体育场拍摄，以..."
96,黑客帝国,1999,2000-01-14,动作 科幻,136.0,82,英语,拉娜·沃卓斯基,莉莉·沃卓斯基,基努·里维斯 劳伦斯·菲什伯恩 凯瑞-安·莫斯 雨果·维文 格洛丽亚·福斯特 乔·潘托里亚诺...,欢迎来到现实世界,不久的将来，网络黑客尼奥对这个看似正常的现实世界产生了怀疑。他结识了黑客崔妮蒂，并见到了黑客...
97,比莉·艾利什：模糊世界,2021,2021-02-26,纪录 音乐,140.0,82,英语,R. J. Cutler,NaN,比莉·艾利什 菲尼亚斯·奥康奈尔 Maggie Baird Patrick O'Connel...,NaN,熟悉的歌声响起，从小到大的她的影像出现，聚焦这个尚未满19岁的年轻歌手的崛起、她那些改变了自...
98,云上情歌,2020,2020-10-09,音乐 剧情 爱情,121.0,82,英语,卡拉·霍尔顿,贾斯汀·贝尔杜尼,芬·奥尔格斯 塞布丽娜·卡彭特 麦迪森·伊瑟曼 内芙·坎贝尔 托马斯·埃弗雷特·斯科特 里尔...,Don't wait for tomorrow to live for today.,美国男孩扎克·索比赫14岁被诊断患有骨肉瘤(18岁去世)，多次手术和化疗并未遏制癌症发展，在...
99,边境奇袭,2025,2025-02-28,动作 冒险 惊悚,85.0,82,西班牙语,Chava Cartas,José Rubén Escalante Méndez,Luis Alberti 诺伊·埃尔南德斯 Leonardo Alonso Luis Cur...,NaN,一场人质营救行动带来了新的敌人，格雷罗上尉和他的精英士兵们必须应对残忍犯罪团伙的埋伏。
100,老男孩,2003,2003-11-21,剧情 惊悚 悬疑 动作,120.0,82,朝鲜语,朴赞郁,黄肇允,崔岷植 刘智泰 姜惠贞 金秉玉 池大汉 吴达洙 李胜欣 尹珍序 吴泰景,15年监禁……5天复仇,女儿生日那天，中年男子吴大修（崔岷植饰）在醉酒回家路上，突遭不明身份的人绑架失踪。就此，他毫...

In [12]:
test_df[test_df["年份"] >= 2000]
test_df[(test_df["语言"].isin(["英语","日语"])) & (test_df["评分"].between(80,90))]
test_df[(test_df["语言"] == "英语") | (test_df["时长"] >= 250)]

,电影名,年份,上映时间,类型,时长,评分,语言,导演,作者,主演,Slogan,简介
0,肖申克的救赎,1994,1994-09-23,剧情 犯罪,142.0,87,英语,弗兰克·德拉邦特,斯蒂芬·金,蒂姆·罗宾斯 摩根·弗里曼 鲍勃·冈顿 威廉姆·赛德勒 克兰西·布朗 吉尔·贝罗斯 小詹姆斯...,恐惧会将你囚禁，希望则能让你获得自由。,安迪·杜佛兰被错判谋杀妻子及其情人，在缅因州肖申克服刑，判处两项无期徒刑接连执行。影片背景设...
1,教父,1972,1972-03-24,剧情 犯罪,175.0,87,英语,弗朗西斯·科波拉,马里奥·普佐,马龙·白兰度 阿尔·帕西诺 詹姆斯·凯恩 罗伯特·杜瓦尔 理查德·萨尔瓦托雷·卡斯特拉诺 黛...,一份你无法拒绝的邀约。,40年代的美国，“教父”维托·唐·柯里昂是黑手党柯里昂家族的首领，带领家族从事非法的勾当，但...
2,教父2,1974,1974-12-20,剧情 犯罪,200.0,86,英语,弗朗西斯·科波拉,马里奥·普佐,阿尔·帕西诺 罗伯特·杜瓦尔 黛安·基顿 罗伯特·德尼罗 约翰·卡扎尔 塔莉亚·夏尔 李·斯...,柯里昂帝国的兴衰史。,作为《教父》的续篇，影片延续了科莱昂家族两代权力交替的史诗。科波拉在第二部分中讲述了两条故事...
3,辛德勒的名单,1993,2019-04-06,剧情 历史 战争,195.0,86,英语,史蒂文·斯皮尔伯格,托马斯·肯尼利,连姆·尼森 本·金斯利 拉尔夫·费因斯 卡罗琳·古道尔 乔纳森·萨加尔 艾伯斯·戴维斯 马尔...,谁拯救了一条生命，谁就拯救了整个世界。,1939年，波兰在纳粹德国的统治下，党卫军对犹太人进行了隔离统治。德国商人奥斯卡·辛德勒（连...
4,¿Quieres ser mi hijo?,2023,2023-09-21,喜剧 爱情,100.0,86,英语,Ihtzi Hurtado,NaN,Ludwika Paleta Juanpa Zurita 埃尔南·门多萨 Harold Az...,NaN,"Lu, a conformist woman in her forties, learns ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,绣巾蒙面盗,1946,1946-08-30,犯罪 悬疑 惊悚,103.0,73,英语,Robert Siodmak,欧内斯特·米勒·海明威,Edmond O'Brien 伯顿·兰开斯特 Ava Gardner Albert Dekk...,她能与任何黑帮分子匹敌！,两个神秘的来客来到乔治开设的快餐店等待每夜来此吃晚餐的皮特·拉恩，他们以枪威胁乔治支走所有客...
1996,守望者,2009,2009-03-06,悬疑 动作 科幻,215.0,74,英语,扎克·施奈德,大卫·海特,玛琳·阿克曼 帕特里克·威尔森 比利·克鲁德普 马修·古迪 杰基·厄尔·哈利 杰弗里·迪恩·...,不论我们做什么，正义都会降临到我们每一个人身上,由于邪恶势力肆意蔓延，一群具有超群实力的正义之士挺身而出，他们戴着面具，身着奇装异服，与各种...
1997,战略大作战,1970,1970-06-23,冒险 喜剧 战争,144.0,74,英语,Brian G. Hutton,特洛伊·肯尼迪-马丁,克林特·伊斯特伍德 特利·萨瓦拉斯 唐纳德·萨瑟兰 唐纳德·杰伊·里克尔斯 约翰·卡罗尔·奥...,They set out to rob a bank... and damn near wo...,第二次世界大战时，一名德军上校被美军俘虏，就在质询德国上校前，美军营地遭到火炮的攻击。然而，...
1998,大毒枭,2001,2001-04-05,犯罪 剧情,124.0,74,英语,泰德·戴米,大卫·麦肯纳,约翰尼·德普 佩内洛普·克鲁兹 弗朗卡·波滕特 瑞切尔·格里菲斯 雷·利奥塔 詹迪·莫拉 克...,based on a true story,一名平凡的美国人乔治戎格（强尼戴普饰）原本只是一个每天为生活奋斗打拼的小市民，但是在短短的几...
1999,飞鸭向前冲,2023,2023-12-08,家庭 喜剧 冒险 动画,93.0,73,英语,本杰明·雷纳,迈克尔·怀特,库马尔·纳贾尼 伊丽莎白·班克斯 卡斯帕·詹宁斯 特雷西·加扎尔 奥卡菲娜 卡罗·凯恩 科甘...,特立鸭行 统统欢迎,飞鸭马拉德一家向南迁徙前往热带的牙买加，却意外闯入疯狂大都市纽约？在紧张刺激的飞行之旅中，他...